"""Initial migration

Revision ID: 9090180cf67d
Revises: 
Create Date: 2026-01-23 14:22:09.398988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9090180cf67d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Todo_description'), 'Todo', ['description'], unique=False)
    op.create_index(op.f('ix_Todo_end_date'), 'Todo', ['end_date'], unique=False)
    op.create_index(op.f('ix_Todo_id'), 'Todo', ['id'], unique=False)
    op.create_index(op.f('ix_Todo_start_date'), 'Todo', ['start_date'], unique=False)
    op.create_index(op.f('ix_Todo_title'), 'Todo', ['title'], unique=False)
    op.drop_index(op.f('ix_todos_description'), table_name='todos')
    op.drop_index(op.f('ix_todos_end_date'), table_name='todos')
    op.drop_index(op.f('ix_todos_id'), table_name='todos')
    op.drop_index(op.f('ix_todos_start_date'), table_name='todos')
    op.drop_index(op.f('ix_todos_title'), table_name='todos')
    op.drop_table('todos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('end_date', sa.DATETIME(), nullable=False),
    sa.Column('completed', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todos_title'), 'todos', ['title'], unique=False)
    op.create_index(op.f('ix_todos_start_date'), 'todos', ['start_date'], unique=False)
    op.create_index(op.f('ix_todos_id'), 'todos', ['id'], unique=False)
    op.create_index(op.f('ix_todos_end_date'), 'todos', ['end_date'], unique=False)
    op.create_index(op.f('ix_todos_description'), 'todos', ['description'], unique=False)
    op.drop_index(op.f('ix_Todo_title'), table_name='Todo')
    op.drop_index(op.f('ix_Todo_start_date'), table_name='Todo')
    op.drop_index(op.f('ix_Todo_id'), table_name='Todo')
    op.drop_index(op.f('ix_Todo_end_date'), table_name='Todo')
    op.drop_index(op.f('ix_Todo_description'), table_name='Todo')
    op.drop_table('Todo')
    # ### end Alembic commands ###
