"""Initial_migration_fresh

Revision ID: f18d541e6ed1
Revises: 
Create Date: 2026-01-25 02:28:08.544622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f18d541e6ed1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Todo_description'), 'Todo', ['description'], unique=False)
    op.create_index(op.f('ix_Todo_end_date'), 'Todo', ['end_date'], unique=False)
    op.create_index(op.f('ix_Todo_id'), 'Todo', ['id'], unique=False)
    op.create_index(op.f('ix_Todo_start_date'), 'Todo', ['start_date'], unique=False)
    op.create_index(op.f('ix_Todo_title'), 'Todo', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Todo_title'), table_name='Todo')
    op.drop_index(op.f('ix_Todo_start_date'), table_name='Todo')
    op.drop_index(op.f('ix_Todo_id'), table_name='Todo')
    op.drop_index(op.f('ix_Todo_end_date'), table_name='Todo')
    op.drop_index(op.f('ix_Todo_description'), table_name='Todo')
    op.drop_table('Todo')
    # ### end Alembic commands ###
